### ISSUE TITLE
Proper tablet design

### ISSUE THREAD

**Issue by caarmen** [caarmen/scrumchatter#29]
For example:
In one screen, show the list of meetings on the left, and the currently selected meeting on the right.

**Comment by Rolinh** [comment]
To add to this: lists, such as the members list, are too small for a tablet layout. It makes it hard to click on the buttons and it is even more difficult to match an action button to a member.

**Comment by caarmen** [comment]
Thanks @Rolinh for pointing this out. Indeed the font sizes were incorrect.

I've released a new version 1.5.0. It adapts the layout for tablets and changes the font size for the member names.  I was only able to test on emulators though (I don't have any physical tablet).  Let me know if you have any issues still or have further suggestions.

Cheers :)

**Comment by Rolinh** [comment]
Hi @caarmen,

Very nice! I'll test it during our daily stand-up soon and report to you then.
I indeed have other minor issues but I'll open new ones for that (or PR if I manage to get time to hack on your project!).

Cheers
