### ISSUE TITLE
onboarding suggestion: create team members on the fly

### ISSUE THREAD

**Issue by Cathryne** [caarmen/scrumchatter#36]
Upon first start of the app, the Meetings screen is presented, but creating a meeting does not work without first adding someone to the default team. How about adding:
- either a welcome screen that guides new users through these steps,
- or a default team member (which then requires a renaming option) automatically adding when creating a meeting, like it is already done for the "Team A"?

**Comment by caarmen** [comment]
A year and a half later, this is now available :)  When you launch the app for the first time, Team A contains two team members.

Team members may be renamed, just by tapping on them in the member list.
