### ISSUE TITLE
please, mark explicitly that the app doesn't use voice biometry

### ISSUE THREAD

**Issue by KOLANICH** [caarmen/scrumchatter#41]
Because when I had read the description in f-droid the first thing I thought was voice biometry, which can be used to distinguish speakers.

**Comment by caarmen** [comment]
Hello!

Many thanks for your indeed relevant feedback.

I have added a note to the play store description (may take a few hours to become visible) and the readme in this repo. I also have submitted a merge request to update the description on f-droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/671

Cheers

**Comment by KOLANICH** [comment]
P.S. Have you thought about incorporating some FOSS implementation? I have googled a bit and found at least one in Java and one in C++.

**Comment by caarmen** [comment]
Thanks for the idea.  I'm currently not adding enhancements to this app.  I may occasionally do some quick bug fixes, but this looks like a big feature. Check the "Maintenance" section of the README :)

Thanks for the interest though.
