### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by abdulmalikkhan655** [caarmen/scrumchatter#68]
Hello, @caarmen I want to contribute in "scrumchatter" so i  want to designed a new logo for "scrumchatter" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by ggcarlosr** [comment]
Hello friend, I am also available to join by presenting a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by caarmen** [comment]
Hi @abdulmalikkhan655.  Many thanks for the offer, but right now I'm not looking for a new logo. Good luck with your future logo designs on other projects! 😄
