### ISSUE TITLE
 Affix of data backup,data restore and recovery data into scrum chatter

### ISSUE THREAD

**Issue by dzamizain** [caarmen/scrumchatter#70]
Component
scrum chatter is an app using for meetings.we can see who chatters the most high in meetings.after the meeting we can View average and total speaking time of members for all recorded meetings.and we can share this record to other to make a statement or decision at the end of meeting.
and the underlying flaws of this app are very visible because doesn't use the microphone to automatically detect when a person speaking.a client must press on play button when a member speaks.
We can import database if we needs.and
I think this app quite complete.

Proposal
has been using this app in couple of days.there has something feature didn't complete in this app and I have complaint when using. the PO might be want to enhance the application, so I suggest some idea into this app to implemented the following feature.
1.data backup
2.data restore
3.recovery data

Data Backup is a process of duplicating or copying data from one device or storage media to media devices or other systems offline or online to secure data by copying data.

Data Restore is the process of restoring a data or file to the original place. As the principle of backup, restore is to restore data, files, or system in the original state, There are two types of data restore, the first is system restore and the second is the system image backup.

Recovery data is needs because Usually a system becomes corrupted or errors can be caused through internal and external factors

Mock up
Picture illustration of my suggestion on
Data backup in this app.
 ![PicsArt_07-28-09.12.42.png](https://cdn.steemitimages.com/DQmbzxNnPZAdV5jzSGSxJyDUXLZwaBTyAmG2G7Vmj8Fo8bG/PicsArt_07-28-09.12.42.png)
 Data restore illustration from me.might be look like this
 ![PicsArt_07-28-09.13.18.png](https://cdn.steemitimages.com/DQmWHUzofSJ3ziWkBLjksoUo58AxNRU86UfCLTCx5VZuDHb/PicsArt_07-28-09.13.18.png)
  And last implemented Recovery data Like in this picture below
 ![PicsArt_07-29-11.45.57.png](https://cdn.steemitimages.com/DQmcfbFacmNNFRJwhsons1J5kvbp57iMQbW2XLMh5oerJoj/PicsArt_07-29-11.45.57.png)

Benefits

the use of backup data is when one of the storage media is damaged, lost, or exposed to the virus, the important data is not lost, not damaged, and whenever and wherever it can be accessed easily.

Backup has a main function and some other functions. Data backup function is to save data from the risk of damage, lost or inaccessible data back. Data stored in not only one storage medium will provide a sense of security because the data is stored properly. Backup can also function as a disaster recovery plan, which is to restore data.Basically backup aims to restore lost data, corrupted, corrupted, or exposed to the virus.user will never know what things may happen to their storage media , it would be better to have not just one data storage medium. So when at any time the main data is lost, users can still restore the data in full without any damage or loss.

Restore data will restore data, files, or system in the original state.So if users want to restore the configuration of programs that have been deleted become as usual, can do system restore.

recovery function is to restore the state of a system in certain cases. Usually a system becomes corrupted or errors can be caused through internal and external factors. From internal factors for example due to negligence of human or human error, hardware damage, or lack of maintenance and maintenance. While external factors that can affect system damage can occur because the system is exposed to the virus. So how the system should be free and clean from virus infection so that the system can re-operate as before and can be functioned properly and maximally.

**Comment by caarmen** [comment]
The app already allows the user to backup and restore data. You can backup the data with the "share" function and restore it with the db import function.
