### ISSUE TITLE
add graphs to display stats

### ISSUE THREAD

**Issue by pmarois** [caarmen/scrumchatter#9]
That would be a good idea to have place to display some graphs that would show some data over the time (evolution of total time spoken, of each people time spoken etc...)

**Comment by caarmen** [comment]
Charts are available in 1.3.0.  Currently in staged rollout on the Play Store.

* Line chart of meeting duration over time
* Stacked column chart of member speaking time, over time
* Pie chart of average speaking time per member, for all meetings
* Pie chart of total speaking time per member, for all meetings
* Column chart for one meeting, showing the ranking of members

![meetingstats](https://cloud.githubusercontent.com/assets/1731388/15521633/10e8fc8e-220d-11e6-8699-0e5d7ba2b05b.png)
![memberstats](https://cloud.githubusercontent.com/assets/1731388/15521644/152b8848-220d-11e6-9a25-a2f0869adc92.png)
![one-meeting](https://cloud.githubusercontent.com/assets/1731388/15521648/1a64b0e6-220d-11e6-8f8a-4306819dc3f9.png)

**Comment by caarmen** [comment]
Note, the last column chart has some display issues regarding the labels.  This has been reported here: https://github.com/lecho/hellocharts-android/issues/287
